### ISSUE TITLE
is it possible to release v1.1.3 ?

### ISSUE THREAD

**Issue by dirablue** [qwantix/serverless-athena#7]
Hi @qwantix 
Thank you for making this plugin.

could I ask if you ready to release v1.1.3 from master branch ?
I would like to use "enabled" flag which doesn't exist in v1.1.2

thanks

**Comment by qwantix** [comment]
@dirablue sorry for the delay.

I just released version 2.0.0-alpha.0.

**Comment by dirablue** [comment]
@qwantix 
Hi Thank you so much for your work !
